export class Soundtrack{
 ctx:AudioContext;master:GainNode;timer:ReturnType<typeof setInterval>|null=null;beat=0;next=0;
 constructor(){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.18;this.master.connect(this.ctx.destination)}
 tone(freq:number,time:number,dur:number,type:OscillatorType='sawtooth',volume=.1){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.001,time+dur);o.connect(g);g.connect(this.master);o.start(time);o.stop(time+dur+.01)}
 noise(time:number,dur:number,vol:number){const b=this.ctx.createBuffer(1,this.ctx.sampleRate*dur,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();s.buffer=b;f.type='highpass';f.frequency.value=1500;g.gain.value=vol;s.connect(f);f.connect(g);g.connect(this.master);s.start(time)}
 guitar(freq:number,t:number){const curve=new Float32Array(256);for(let i=0;i<256;i++){const x=i*2/255-1;curve[i]=Math.tanh(x*20)}const dist=this.ctx.createWaveShaper(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain();dist.curve=curve;filter.type='lowpass';filter.frequency.value=2600;gain.gain.setValueAtTime(.17,t);gain.gain.exponentialRampToValueAtTime(.001,t+.13);dist.connect(filter);filter.connect(gain);gain.connect(this.master);for(const mult of [1,1.5,2]){const o=this.ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq*mult;o.connect(dist);o.start(t);o.stop(t+.15)}}
 start(){void this.ctx.resume();if(this.timer)return;this.next=this.ctx.currentTime;this.timer=setInterval(()=>{while(this.next<this.ctx.currentTime+.15){const t=this.next,n=this.beat%32;const riff=[0,0,0,3,0,0,6,5,0,0,0,3,0,5,3,1];const freq=65.4*Math.pow(2,riff[n%16]/12);this.guitar(freq,t);this.tone(freq/2,t,.12,'triangle',.3);if(n%4===0||n%8===3){this.tone(75,t,.15,'sine',.8);this.tone(40,t,.19,'sine',.5)}if(n%8===4)this.noise(t,.15,.6);this.noise(t,.025,n%2?.12:.22);if(n>=24)this.tone(freq*4,t,.1,'square',.025);this.beat++;this.next+=60/152/4}},40)}
 effect(kind:string){const t=this.ctx.currentTime;if(kind==='hit'||kind==='explosion'){this.noise(t,.14,.6);this.tone(kind==='explosion'?45:95,t,.13,'sawtooth',.5)}else if(kind==='block'){this.tone(630,t,.09,'triangle',.5)}else if(kind==='finisher'||kind==='power'){for(let i=0;i<8;i++)this.tone(110*2**(i/4),t+i*.05,.17,'sawtooth',.15)}}
 mute(muted:boolean){this.master.gain.setTargetAtTime(muted?0:.18,this.ctx.currentTime,.02)}
 dispose(){if(this.timer)clearInterval(this.timer);void this.ctx.close()}
}
