'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Volume2,VolumeX,ArrowRight,Play,RotateCcw,ArrowLeft} from 'lucide-react';
import {Arena} from './arena';
import {Combat,type Input,type Action} from './combat';
import {fighters,stages,type Mode} from './data';
import {Soundtrack} from './audio';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Props={p1:number;p2:number;stage:number;mode:Mode;sound:boolean;toggleSound:()=>void;menu:()=>void;level:number;next:()=>void};
const actionKeys:Record<string,[number,Action]>={KeyJ:[0,'light'],KeyK:[0,'heavy'],KeyL:[0,'special'],KeyO:[0,'finish'],KeyU:[0,'power'],ShiftLeft:[0,'dash'],Numpad1:[1,'light'],Numpad2:[1,'heavy'],Numpad3:[1,'special'],Numpad4:[1,'dash'],Numpad5:[1,'power'],Numpad6:[1,'finish'],Digit1:[1,'light'],Digit2:[1,'heavy'],Digit3:[1,'special'],Digit4:[1,'dash'],Digit5:[1,'power'],Digit6:[1,'finish']};
export default function Battle(props:Props){
 const host=useRef<HTMLDivElement>(null),engine=useRef<Combat|null>(null),audio=useRef<Soundtrack|null>(null),pressed=useRef(new Set<string>()),queued=useRef<(Action|undefined)[]>([undefined,undefined]);const[paused,setPaused]=useState(false),[revision,setRevision]=useState(0),[error,setError]=useState('');const pauseRef=useRef(false);pauseRef.current=paused;const soundRef=useRef(props.sound);soundRef.current=props.sound;
 const[view,setView]=useState({hp:[100,100],guard:[100,100],energy:[0,0],wins:[0,0],boost:[0,0],combo:[0,0],timer:99,round:1,phase:'intro',winner:-1,banner:'ROUND 1'});
 useEffect(()=>{const game=new Combat(props.p1,props.p2,props.mode,.28+props.level*.085);engine.current=game;let arena:Arena;try{arena=new Arena(host.current!,props.stage,[props.p1,props.p2])}catch(e){setError('The arena needs WebGL 2. Enable hardware acceleration or try a desktop browser.');return}let disposed=false,frame=0,last=performance.now(),acc=0,hud=0,banner='ROUND 1',bannerUntil=2.2;setView({hp:[100,100],guard:[100,100],energy:[0,0],wins:[0,0],boost:[0,0],combo:[0,0],timer:99,round:1,phase:'intro',winner:-1,banner});pressed.current.clear();queued.current=[undefined,undefined];
 const keydown=(e:KeyboardEvent)=>{if(e.code==='Escape'){setPaused(p=>!p);return}if(pauseRef.current)return;if(actionKeys[e.code]||['KeyW','KeyA','KeyS','KeyD','KeyI','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Numpad0','Digit0'].includes(e.code)){e.preventDefault();pressed.current.add(e.code);if(!e.repeat&&actionKeys[e.code]){const[n,a]=actionKeys[e.code];queued.current[n]=a}}};
 const keyup=(e:KeyboardEvent)=>{pressed.current.delete(e.code)};const blur=()=>{pressed.current.clear();queued.current=[undefined,undefined];setPaused(true)};const visibility=()=>{if(document.hidden)blur()};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 const loop=(now:number)=>{if(disposed)return;const dt=Math.min((now-last)/1000,.06);last=now;const events=[];if(!pauseRef.current){acc+=dt;while(acc>=1/60){const k=pressed.current;const input:Input[]=[{left:k.has('KeyA'),right:k.has('KeyD'),jump:k.has('KeyW'),crouch:k.has('KeyS'),block:k.has('KeyI'),action:queued.current[0]},{left:k.has('ArrowLeft'),right:k.has('ArrowRight'),jump:k.has('ArrowUp'),crouch:k.has('ArrowDown'),block:k.has('Numpad0')||k.has('Digit0'),action:queued.current[1]}];queued.current=[undefined,undefined];game.step(1/60,input);events.push(...game.events);acc-=1/60}game.events=events;for(const e of events){if(soundRef.current)audio.current?.effect(e.type);if(e.text&&['start','round','special','power','finisher','break'].includes(e.type)){banner=e.text;bannerUntil=game.elapsed+(e.type==='finisher'?1.6:e.type==='round'?2.6:1)}}if(game.phase==='intro'){banner=`ROUND ${game.round}`;bannerUntil=game.elapsed+.1}arena.update(game,dt);game.events=[];hud+=dt;if(hud>.05){hud=0;setView({hp:game.players.map(p=>p.hp),guard:game.players.map(p=>p.guard),energy:game.players.map(p=>p.energy),boost:game.players.map(p=>p.boost),combo:game.players.map(p=>p.combo),wins:[...game.wins],timer:Math.ceil(game.timer),round:game.round,phase:game.phase,winner:game.winner,banner:game.elapsed<bannerUntil?banner:''})}}frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);
 return()=>{disposed=true;cancelAnimationFrame(frame);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);arena.dispose();engine.current=null};
 },[props.p1,props.p2,props.mode,props.stage,props.level,revision]);
 useEffect(()=>{if(props.sound&&!audio.current){audio.current=new Soundtrack();audio.current.start()}audio.current?.mute(!props.sound||paused)},[props.sound,paused]);useEffect(()=>()=>audio.current?.dispose(),[]);
 const rematch=()=>{setPaused(false);setRevision(r=>r+1)};
 const touch=(code:string,down:boolean)=>{if(down){pressed.current.add(code);if(actionKeys[code]){const[n,a]=actionKeys[code];queued.current[n]=a}}else pressed.current.delete(code)};
 return <main className="battle-screen"><div ref={host} className="arena-canvas"/>{error&&<div className="arena-error"><h2>ARENA UNAVAILABLE</h2><p>{error}</p><button className="fight-button" onClick={props.menu}>BACK TO SELECT</button></div>}
 <div className="battle-top"><span className="brand">RIFT<span>//</span>RIOT</span><span>{props.mode==='arcade'?`ARCADE / BATTLE ${props.level+1} OF 11`:props.mode==='local'?'LOCAL VERSUS':'VERSUS CPU'} <b>•</b> {stages[props.stage].name}</span><div><button aria-label="Toggle soundtrack" onClick={props.toggleSound}>{props.sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button aria-label="Pause match" onClick={()=>setPaused(true)}><Pause size={19}/></button></div></div>
 <div className="combat-hud">{[props.p1,props.p2].map((id,n)=><div key={n} className={`player-hud p${n+1}`} style={{'--player-color':fighters[id].color} as React.CSSProperties}><div className="hud-name"><span>{n===0?'P1':props.mode==='local'?'P2':'CPU'} <strong>{fighters[id].name}</strong></span><span className="round-pips">{[0,1].map(i=><i className={view.wins[n]>i?'won':''} key={i}/>)}</span></div><div className="health-track"><div style={{width:`${view.hp[n]}%`}}/></div><div className="guard-line"><span>GUARD</span><i><b style={{width:`${view.guard[n]}%`}}/></i><span>{Math.ceil(view.hp[n])}</span></div></div>)}<div className="round-clock"><strong>{String(view.timer).padStart(2,'0')}</strong><span>ROUND {view.round}</span></div></div>
 {view.banner&&view.phase!=='over'&&<div key={view.banner} className={`battle-callout ${view.banner==='K.O.'?'ko':''}`} aria-live="polite"><small>BREAK YOUR FATE</small><strong>{view.banner}</strong></div>}
 <div className="combo-row">{view.combo.map((c,n)=><div key={n}>{c>1&&<><strong>{c}</strong><span>HIT<br/>COMBO</span></>}</div>)}</div>
 <div className="energy-hud">{[0,1].map(n=><div key={n} className={`energy-panel energy-${n}`}><span>{view.boost[n]>0?'OVERDRIVE ACTIVE':view.energy[n]>=100?'FINISHER READY':'RIOT ENERGY'} <b>{Math.floor(view.energy[n])}%</b></span><div className={view.energy[n]>=100?'energy-track charged':'energy-track'}><i style={{width:`${view.energy[n]}%`}}/></div><small>20 SPECIAL <b>/</b> 50 OVERDRIVE <b>/</b> 100 FINISHER</small></div>)}</div>
 <div className="keyboard-strip"><span><kbd>A D</kbd> MOVE <kbd>W</kbd> JUMP <kbd>S</kbd> CROUCH</span><span><kbd>J</kbd> LIGHT <kbd>K</kbd> HEAVY <kbd>L</kbd> SPECIAL <kbd>I</kbd> BLOCK <kbd>SHIFT</kbd> DASH <kbd>U</kbd> POWER <kbd>O</kbd> FINISH</span></div>
 <div className="touch-controls">{[['KeyA','←'],['KeyD','→'],['KeyW','↑'],['KeyS','↓'],['KeyI','GUARD'],['ShiftLeft','DASH'],['KeyJ','J'],['KeyK','K'],['KeyL','L'],['KeyU','UP'],['KeyO','FIN']].map(([code,label])=><button key={code} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touch(code,true)}} onPointerUp={()=>touch(code,false)} onPointerCancel={()=>touch(code,false)}>{label}</button>)}</div>
 {view.phase==='over'&&<section className="victory-panel"><span className="eyebrow">{props.mode==='arcade'&&view.winner===0&&props.level===10?'ARCADE CHAMPION':'THE DUST HAS SETTLED'}</span><h1>{fighters[view.winner===0?props.p1:props.p2].name}<br/><em>WINS.</em></h1><p>“{fighters[view.winner===0?props.p1:props.p2].quote}”</p><div className="final-score">{view.wins[0]} <span>—</span> {view.wins[1]}</div>{props.mode==='arcade'&&view.winner===0&&props.level<10?<button className="fight-button" onClick={props.next}>NEXT CHALLENGER <ArrowRight/></button>:<button className="fight-button" onClick={rematch}><RotateCcw size={20}/> REMATCH</button>}<button className="return-button" onClick={props.menu}><ArrowLeft size={16}/> CHARACTER SELECT</button></section>}
 <Dialog open={paused&&!error} onOpenChange={setPaused}><DialogContent className="pause-dialog"><DialogTitle className="pause-title">TAKE A BREATHER.</DialogTitle><DialogDescription>The fight will wait for you.</DialogDescription><button className="fight-button" onClick={()=>setPaused(false)}>RESUME <Play size={20}/></button><button className="outline-button" onClick={rematch}><RotateCcw size={17}/> RESTART MATCH</button><button className="outline-button" onClick={props.menu}><ArrowLeft size={17}/> CHARACTER SELECT</button></DialogContent></Dialog>
 </main>
}
