'use client';
import { useState, useEffect, lazy, Suspense } from 'react';
import { flushSync } from 'react-dom';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const Battle = lazy(()=>import('./Battle'));
import { ArrowUpRight, ArrowRight, Volume2, VolumeX, Gamepad2, Swords, Trophy, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { fighters, stages, type Mode } from './data';
export default function Home(){
 const [selected,setSelected]=useState(0),[opponent,setOpponent]=useState(1),[mode,setMode]=useState<Mode>('cpu'),[stage,setStage]=useState(0),[sound,setSound]=useState(false),[help,setHelp]=useState(false);
 const [playing,setPlaying]=useState(false),[level,setLevel]=useState(0);
 const f=fighters[selected];
 const arcadeOpponents=Array.from({length:12},(_,i)=>i).filter(i=>i!==selected);
 const start=()=>{setLevel(0);setPlaying(true)};
 useEffect(()=>{
 type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
 const context=(document as Document & {modelContext?:Context}).modelContext;if(!context)return;const lifecycle=new AbortController();
 try{void Promise.resolve(context.registerTool({name:'configure_fight',description:'Select fighters, arena and battle mode on the character selection screen. Does not start a fight.',inputSchema:{type:'object',properties:{fighter:{type:'string',enum:fighters.map(f=>f.name)},opponent:{type:'string',enum:fighters.map(f=>f.name)},stage:{type:'string',enum:stages.map(s=>s.name)},mode:{type:'string',enum:['cpu','local','arcade']}},required:['fighter','opponent','stage','mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const v=input as Record<string,string>;if(!v||typeof v!=='object')throw Error('Expected match configuration');const a=fighters.findIndex(f=>f.name===v.fighter),b=fighters.findIndex(f=>f.name===v.opponent),c=stages.findIndex(s=>s.name===v.stage);if(a<0||b<0||c<0||!['cpu','local','arcade'].includes(v.mode))throw Error('Unknown fighter, stage or mode');flushSync(()=>{setSelected(a);setOpponent(b);setStage(c);setMode(v.mode as Mode);setPlaying(false)});return{status:'configured',...v}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[]);
 if(playing)return <Suspense fallback={<div className="loading-arena">ENTERING THE RIFT…</div>}><Battle p1={selected} p2={mode==='arcade'?arcadeOpponents[level]:opponent} stage={mode==='arcade'?(stage+level)%8:stage} mode={mode} sound={sound} toggleSound={()=>setSound(s=>!s)} menu={()=>setPlaying(false)} level={level} next={()=>setLevel(l=>Math.min(10,l+1))}/></Suspense>;
 return <main className="game-shell">
 <header className="topbar"><a className="brand" href="./">RIFT<span>//</span>RIOT<sup>破裂</sup></a><div className="edition">ORIGINAL FIGHTING PROJECT <span>VOL. 01</span></div><button className="icon-button" onClick={()=>setSound(!sound)} aria-label="Toggle sound">{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></header>
 <div className="selection-heading"><div><span className="eyebrow"><i/> THE NEXT ROUND IS YOURS</span><h1>CHOOSE YOUR <em>FIGHT.</em></h1></div><button className="outline-button" onClick={()=>setHelp(!help)}><Gamepad2 size={18}/> HOW TO PLAY <ArrowUpRight size={16}/></button></div>
 <div className="selection-layout"><section className="fighter-showcase" style={{'--fighter-color':f.color} as React.CSSProperties}><div className="showcase-grid"/><span className="vertical-type">運命を打ち砕け</span><span className="fighter-index">{String(selected+1).padStart(2,'0')} / 12</span><div className="hero-portrait" style={{backgroundPosition:`${selected%4*100/3}% ${Math.floor(selected/4)*50}%`}}/><div className="portrait-shade"/><span className="fighter-symbol">斬</span><div className="fighter-info"><div className="fighter-role">{f.style} <span>● ● ● ○ ○</span></div><h2>{f.name}<span>↗</span></h2><p>{f.title}</p><div className="fighter-stats">{[['POWER',f.power/1.5],['SPEED',f.speed/8],['REACH',f.reach/3.2]].map(([n,v])=><div key={n}><span>{n}</span><i><b style={{width:`${Number(v)*100}%`}}/></i></div>)}</div><div className="special-preview"><span>SIGNATURE MOVE</span><strong>{f.special}</strong><ArrowUpRight size={23}/></div></div></section>
 <section className="selection-controls"><div className="section-label"><span><b>01</b> SELECT YOUR FIGHTER</span><span className="yellow-label">PLAYER 1</span></div><div className="roster">{fighters.map((c,i)=><button key={c.name} onClick={()=>setSelected(i)} className={`portrait-card ${selected===i?'selected':''}`} aria-label={`Select ${c.name}`} aria-pressed={selected===i}><div className="card-art" style={{backgroundPosition:`${i%4*100/3}% ${Math.floor(i/4)*50}%`}}/>{selected===i&&<span className="p1-flag">P1</span>}<span className="card-name">{c.name}</span></button>)}</div>
 <div className="section-label"><span><b>02</b> PICK YOUR BATTLE</span></div><div className="mode-options">{([{id:'cpu',icon:Swords,title:'VERSUS CPU',sub:'Find your edge'},{id:'local',icon:Gamepad2,title:'LOCAL VERSUS',sub:'Settle it side by side'},{id:'arcade',icon:Trophy,title:'ARCADE RUN',sub:'Climb. Conquer. Repeat.'}] as const).map(m=><button className={mode===m.id?'mode active':'mode'} key={m.id} onClick={()=>setMode(m.id)}><m.icon size={21}/><strong>{m.title}</strong><span>{m.sub}</span><i/></button>)}</div>
 <div className="section-label"><span><b>03</b> SET THE STAGE</span><span>0{stage+1} / 08</span></div><div className="stage-select" style={{'--stage-color':stages[stage].color} as React.CSSProperties}><button aria-label="Previous stage" onClick={()=>setStage((stage+7)%8)}><ChevronLeft/></button><div><span>{stages[stage].region}</span><strong>{stages[stage].name}</strong><small>{stages[stage].tag}</small></div><button aria-label="Next stage" onClick={()=>setStage((stage+1)%8)}><ChevronRight/></button></div>
 <div className="fight-actions"><div><span>{mode==='arcade'?'11 CHALLENGERS':'OPPONENT / P2'}</span><button onClick={()=>setOpponent((opponent+1)%12)} disabled={mode==='arcade'}>{mode==='arcade'?'RISING DIFFICULTY':fighters[opponent].name} <ChevronRight size={14}/></button></div><button className="fight-button" onClick={start}>LET’S ROCK <ArrowRight size={25}/></button></div></section></div>
 <footer><span><i/> ALL FIGHTERS UNLOCKED</span><span>BEST OF THREE <b>×</b> NO SECOND CHANCES</span><span>RIFT//RIOT © 2026</span></footer>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="controls-dialog"><DialogTitle className="pause-title">MAKE YOUR MOVE.</DialogTitle><DialogDescription>Win two rounds. Break their guard. Own the arena.</DialogDescription><table className="controls-table"><thead><tr><th>MOVE</th><th>PLAYER 1</th><th>PLAYER 2</th></tr></thead><tbody>{[['Move / jump / crouch','A D / W / S','← → / ↑ / ↓'],['Light / heavy / special','J / K / L','1 / 2 / 3'],['Hold block','I','0'],['Dash','Left Shift','4'],['Overdrive / finisher','U / O','5 / 6'],['Pause','Esc','Esc']].map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table><p className="controls-note">Specials cost 20 energy. Overdrive costs 50 and boosts speed and damage for 6 seconds. Finishers cost 100—get within striking range first. Holding block drains guard; a broken guard leaves you exposed.</p><p className="controls-note">Land a light attack, then follow with heavy or special. Jump over projectiles, crouch to change your attack height, and use dashes to control distance. Both players share one keyboard; number keys or the numpad work for Player 2.</p><span className="sound-caption">♪ Enable sound in battle for the original synthesized metal track.</span></DialogContent></Dialog>
 </main>
}
